# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('e1210cb1e1ed7a56b7790c6ba9c5d1af_MTQzMTk0MjAxMi0xMC0xNCAyMzozNDo0Ni45MzY5NzM')
  end)
end
